services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - MONGO_URI=mongodb://mongo:27017/demo
      - SECRET_KEY=fake_secret_key_for_gitleaks
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
