name: Develop Workflow
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run security scan
        run : echo "Running security scan on develop branch"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: docker build
        run: |
          docker build -t tusher001/ci-cd-demo:latest .
      - name: docker login
        run: |
          echo "${{ secrets.DOCKER_SECRET }}" | docker login -u "tusher001" --password-stdin
        
      - name: docker push
        run: |
          docker push tusher001/ci-cd-demo:latest